---

- name: assert | Test if forensics_local_storage_path is set correctly
  ansible.builtin.assert:
    that:
      - forensics_local_storage_path is defined
      - forensics_local_storage_path is string
    quiet: true

- name: assert | Test if forensics_command_list is set correctly
  ansible.builtin.assert:
    that:
      - forensics_command_list is defined
      - forensics_command_list is iterable
    quiet: true

- name: assert | Test if item in forensics_command_list is set correctly
  ansible.builtin.assert:
    that:
      - item is defined
      - item is string
    quiet: true
  loop: "{{ forensics_command_list }}"

- name: assert | Test if forensics_directory_list is set correctly
  ansible.builtin.assert:
    that:
      - forensics_directory_list is defined
      - forensics_directory_list is iterable
    quiet: true

- name: assert | Test if item in forensics_directory_list is set correctly
  ansible.builtin.assert:
    that:
      - item is defined
      - item is string
    quiet: true
  loop: "{{ forensics_directory_list }}"

- name: assert | Test if forensics_file_list is set correctly
  ansible.builtin.assert:
    that:
      - forensics_file_list is defined
      - forensics_file_list is iterable
    quiet: true

- name: assert | Test if item in forensics_file_list is set correctly
  ansible.builtin.assert:
    that:
      - item is defined
      - item is string
    quiet: true
  loop: "{{ forensics_file_list }}"

- name: assert | Test if forensics_specific_file_list is set correctly
  ansible.builtin.assert:
    that:
      - forensics_specific_file_list is defined
      - forensics_specific_file_list is iterable
    quiet: true

- name: assert | Test if item in forensics_specific_file_list is set correctly
  ansible.builtin.assert:
    that:
      - item.path is defined
      - item.path is string
      - item.pattern is defined
      - item.pattern is string
    quiet: true
  loop: "{{ forensics_specific_file_list }}"
  loop_control:
    label: "{{ item.path }}"
