---
#
# Ansible managed
#

name: "Dependabot Merge"

on:
  pull_request:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@master"
      - name: Dependabot Auto Merge Action
        uses: buluma/dependabot-auto-merge-action@v2.0.1
